llm:
  groq_deepseek:
    provider: "groq"
    model_name: "deepseek-r1-distill-llama-70b"

  groq_oss:
    provider: "groq"
    model_name: "openai/gpt-oss-120b"

  groq_oss_20b:
    provider: "groq"
    model_name: "openai/gpt-oss-20b"